const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const context=vm.createContext({window:{},document:{readyState:'loading',addEventListener(){}}});
vm.runInContext(fs.readFileSync('delivery-data.js','utf8'),context);
vm.runInContext(fs.readFileSync('delivery.js','utf8'),context);
const select=state=>JSON.parse(vm.runInContext(`JSON.stringify(selectCatalogProducts(${JSON.stringify({query:'',category:'all',filters:[],sort:'default',...state})}).map(p=>p.id))`,context));
assert.deepEqual(select({category:'bebidas'}),['caipirinha-lume','soda-caju']);
assert.deepEqual(select({category:'entradas'}),['croquete-costela']);
assert.equal(select({filters:['under40']}).length,6);
assert.equal(select({sort:'price'})[0],'soda-caju');
assert.deepEqual(select({query:'caju',category:'bebidas',filters:['under40'],sort:'price'}),['soda-caju']);
assert.deepEqual(select({query:'caju',category:'pratos',filters:['under40']}),[]);
assert.deepEqual(select({filters:['vegetarian']}),['massa-trufada']);
assert.deepEqual(select({filters:['alcoholFree']}),['soda-caju']);
assert.deepEqual(select({filters:['promotion']}),['combo-lume-2','executivo-bowl']);
assert.equal(select({filters:['popular']}).length,3);
assert.deepEqual(select({query:'CAIPIRINHA',category:'bebidas',filters:['alcoholFree']}),[]);
assert.deepEqual(select({query:'salmão'}),select({query:'salmao'}));
assert.equal(select({sort:'rating'})[0],'combo-lume-2');
console.log('PASS: 13 catalog regression assertions');
